version: '3'
services:
  kafka:
    build:
      context: .
    volumes:
      - ./data/kafka-logs:/data/kafka-logs
      - ./data/zookeeper:/data/zookeeper
    hostname: kafka
    ports:
      - 2181:2181
      - 9092:9092
    tty: true
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:19092
    depends_on:
      - kafka

